install:
  - choco install gitversion.portable -pre -y

skip_tags: true

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_test:
  - nuget pack Stony.GoogleMaps.Geocoding\Stony.GoogleMaps.Geocoding.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: '*.nupkg'

assembly_info:
  patch: false

deploy:
  - provider: NuGet
    name: nuget.org
    api_key:
      secure: K5gawsVibF7f9rs+VEbdU9mjwI7bv8ollvZ14gFGx+FBoq8MIAPX2UNnWLcogiDp
    on:
      branch: master
      appveyor_repo_tag: true

  - provider: NuGet
    name: myget.org
    server: https://www.myget.org/F/richardthombs/api/v2/package
    api_key:
      secure: myRVmiM63ShAVBMtUXhHmOueUUWh7X1YJJ931kSnMWXkrevwJcur4k2Vdfpchvw1