version: '0.0.{build}'

before_build:
  - nuget restore

after_test:
  - nuget pack Stony.GoogleMaps.Geocoding\Stony.GoogleMaps.Geocoding.nuspec -properties version=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: '*.nupkg'

assembly_info:
  patch: true

deploy:
  - provider: NuGet
    name: nuget.org
    api_key:
      secure: K5gawsVibF7f9rs+VEbdU9mjwI7bv8ollvZ14gFGx+FBoq8MIAPX2UNnWLcogiDp
    on:
      branch: master
